"""empty message

Revision ID: b9ab1a9a2113
Revises: 
Create Date: 2021-11-28 22:41:01.160642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ab1a9a2113'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curpairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_code', sa.String(length=3), nullable=True),
    sa.Column('target_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['curpairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currates')
    op.drop_table('curpairs')
    # ### end Alembic commands ###
